# Generated by Django 5.2.8 on 2026-09-02 15:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Per-user in-range band, replacing the fixed 3.9-10.0 mmol/L thresholds.

    The defaults are those same thresholds, so every existing row keeps the
    behaviour it had and no backfill is needed. They are serialised literally
    rather than as a reference to logs.conversions, so later editing that
    constant cannot rewrite history.
    """


    dependencies = [
        ('users', '0006_backfill_health_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='target_high',
            field=models.DecimalField(decimal_places=3, default=Decimal('10.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='target_low',
            field=models.DecimalField(decimal_places=3, default=Decimal('3.9'), max_digits=6),
        ),
    ]
