# Generated by Django 5.2.8 on 2026-09-03 11:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Per-user bread unit size, defaulting to the 12 g Central-European BE.

    Carbohydrate is still stored in grams on MealLog; this only sets how that
    figure is presented, so there is nothing to backfill.
    """


    dependencies = [
        ('users', '0007_glucose_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='bread_unit_grams',
            field=models.DecimalField(decimal_places=1, default=Decimal('12.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
    ]
