"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Email credentials live in their own file so they can be mounted separately
# from the app config. Provider-neutral: the keys describe SMTP, not a vendor.
email_env = environ.Env()
environ.Env.read_env(BASE_DIR / "email.env")

# check debugging status from .env
DEBUG = env("DEBUG")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# In dev (DEBUG=True) fall back to localhost so no config is needed; in
# production the real hostnames MUST be supplied via the ALLOWED_HOSTS env var.
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS", default=["localhost", "127.0.0.1"] if DEBUG else []
)

# --- Production security hardening ---
# When DEBUG is False these lock the app down for HTTPS. They assume a
# TLS-terminating reverse proxy (nginx/Caddy) sits in front of gunicorn, per the
# Oracle deployment plan. Each toggle defaults to "on in prod, off in dev" but is
# individually overridable via env, so the same settings file serves both.

# Domains allowed to POST to us (Origin check on secure requests). Needed when
# the site is reached via a custom domain/subdomain; e.g.
# CSRF_TRUSTED_ORIGINS=https://glucoread.example.com
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Trust the proxy's X-Forwarded-Proto header so Django knows the original request
# was HTTPS. Only safe when a proxy you control terminates TLS and sets it —
# without this, SECURE_SSL_REDIRECT below would cause an infinite redirect loop.
if env.bool("USE_X_FORWARDED_PROTO", default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True

# HSTS: start at one week in prod so a misconfiguration is recoverable; raise to a
# year (31536000) and consider preload once HTTPS is proven stable.
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS", default=0 if DEBUG else 60 * 60 * 24 * 7
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    "users",
    "landing",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # new
    "anymail",
    "logs",
    "dashboard",
    "main",
    "crispy_forms",
    "crispy_bootstrap5",
]

# --- Email ---
# The backend is chosen by env so the provider can be swapped without a code
# change. Dev prints to the console instead of sending; production defaults to
# SMTP. Nothing here is provider-specific, so moving to a hosted API later
# (e.g. anymail.backends.resend.EmailBackend, once a real domain exists and can
# carry DKIM records) is an env change only.
EMAIL_BACKEND = email_env(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)

EMAIL_HOST = email_env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = email_env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = email_env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = email_env("EMAIL_HOST_USER", default="")
# For Gmail this is an App Password, not the account password (needs 2FA).
EMAIL_HOST_PASSWORD = email_env("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = email_env.int("EMAIL_TIMEOUT", default=10)

# Fall back to the SMTP login rather than a hardcoded personal address, so a
# missing value can never silently send as someone real.
DEFAULT_FROM_EMAIL = email_env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = email_env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

# --- Logging ---
# Without this, Django's default configuration mails unhandled 500s to ADMINS
# and does nothing else. ADMINS was unset, so production errors went nowhere at
# all: no file, no stderr handler, no reporting service. A brute-force run
# against the auth endpoints would have left no trace either.
#
# Everything goes to stdout because the app runs under gunicorn in a container,
# where `docker logs` is the collection point. DJANGO_LOGLEVEL has been defined
# in .env since early on but was read by nothing until now.
DJANGO_LOGLEVEL = env("DJANGO_LOGLEVEL", default="INFO").upper()

# Recipients for unhandled 500s when DEBUG is False. Accepts either a bare
# address or "Name <addr@example.com>", comma separated. Both forms are handled
# because silently dropping a malformed entry would leave you believing alerting
# works when it does not.
def _parse_admin(entry):
    entry = entry.strip()
    if "<" in entry and entry.endswith(">"):
        name, _, addr = entry.partition("<")
        return (name.strip(), addr[:-1].strip())
    return ("", entry)


ADMINS = [_parse_admin(e) for e in env.list("ADMINS", default=[]) if e.strip()]
MANAGERS = ADMINS

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        # Only active when DEBUG is False and ADMINS is populated.
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": False,
        },
    },
    "root": {"handlers": ["console"], "level": DJANGO_LOGLEVEL},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOGLEVEL,
            "propagate": False,
        },
        # 5xx responses. Mailed to ADMINS as well as logged, so a production
        # failure is not silent.
        "django.request": {
            "handlers": ["console", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        # Noisy at DEBUG and it echoes query parameters, so pin it higher.
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # new
    "main.middleware.NoCacheMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Feeds the app shell (nav highlight, header reading chip,
                # time-in-range meter) on every authenticated page.
                "main.context_processors.shell",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URL"),
        conn_max_age=0,
    )
}

# Rate limiting counts requests in the cache, so the cache MUST be shared across
# gunicorn workers. Django's default LocMemCache is per-process: with three
# workers a "5 per minute" limit would silently allow fifteen. The database
# backend uses the Postgres already in the stack and needs no extra service.
# The table is created by `manage.py createcachetable` (idempotent, run at boot).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "glucoread_cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Skopje"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STORAGES = {
    "staticfiles": {"BACKEND": STATICFILES_STORAGE},
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "users.User"  # new

CRISPY_TEMPLATE_PACK = "bootstrap5"


# Where the Django admin lives. Overridable so production can move it off the
# default path that every scanner probes; must end in "/".
ADMIN_PATH = env("ADMIN_PATH", default="admin/")

LOGIN_URL = "glucoread-login"
# Where sign-in and sign-up land when there is no (valid) ?next= to honour.
LOGIN_REDIRECT_URL = "glucoread-dashboard"
